### PR TITLE
Migrate to PEPs 518, 517, 621

### PR DESCRIPTION
**Pull request by jeanas**
When installing this project, pip prints

> DEPRECATION: pypa-docs-theme is being installed using the legacy
> 'setup.py install' method, because it does not have a 'pyproject.toml'
> and the 'wheel' package is not installed. pip 23.1 will enforce this
> behaviour change. A possible replacement is to enable the
> '--use-pep517' option. Discussion can be found at
> https://github.com/pypa/pip/issues/8559

which is ironic for a PyPA project.

Notes:

- `distutils-sig` email removed since the list doesn't exist anymore,
- Change tested by manually inspecting sdists and wheels before and after, and by building the packaging.python.org guide.

### CODE REVIEW

**Comment by jeanas** [comment]
I also noticed that the `python-docs-theme` dependency is not declared, should I add it?

**Comment by pradyunsg** [comment]
> I also noticed that the `python-docs-theme` dependency is not declared, should I add it?

Sure, go ahead. :)

**Comment by jeanas** [comment]
Done :)

**Comment by jeanas** [comment]
Closing this as it isn't useful anymore now that this project is going away.

**Pull request closed without merging**
