### PR TITLE
Limit body width

### LINKED ISSUE #9: Limit body / site width?
Text taking up the whole screen makes it so much harder to read and process. Honestly even though I can see why you want to integrate the branding with python.org, it kinda sucks that all the UX advantages carefully designed into RTD has to go with it.

This is one of the no-brainer things that the RTD theme gets right. (And, I guess, that python.org still gets horribly wrong)

I'd advocate something like
```
div.body {
    max-width: 60em;
}

body {
    max-width: 80em;
}
```

Which looks like this

### PR DESCRIPTION
**Pull request by pradyunsg**
A PR to eventually close #9.

### CODE REVIEW

**Comment by pradyunsg** [comment]
Currently, the width is 1000px and the content now has a right border for visual clarity.

screen shot 2017-11-07 at 12 51 17 pm
screen shot 2017-11-07 at 12 51 06 pm

The right border should probably be removed on screens with width < 1000px; I'll do it if others think having the border is useful in the first place. Ideally, I'd like to change the styling a fair bit but not just yet. :)

**Comment by pradyunsg** [comment]
@jonparrott I have a bunch of improvements that I want to make:

- responsive collapse of the sidebar
- making the sidebar top-to-bottom
- make the pages full height even if the content is small
- cleaning up the footer

These affect both this theme and are inherited from python-docs-theme; should I make issues for them upstream on the repo? If so, I'll make an issue for the limit-width as well then?

**Comment by pradyunsg** [comment]
Aside -- another thing that can be done is move the entire body into the middle, like this:

Like this

**Comment by jonparrott** [comment]
> These are inherited from python-docs-theme; should I make issues for them upstream on the python-docs-theme repo? If so, I'll make an issue for the limit-width as well then?

Yes, that's strongly preferred.

**Comment by pradyunsg** [comment]
> Yes, that's strongly preferred.

idk why but I'm nervous to do that. :|

**Comment by jonparrott** [comment]
If it makes you feel better I'm the one that started the upstream repo?

**Comment by pradyunsg** [comment]
> If it makes you feel better I'm the one that started the upstream repo?

I guess it does.

I just got overwhelmed looking at the watchers list. 🤷‍♂️

**Comment by pfmoore** [comment]
Apparently it's just the Python committers being added automatically - I'm on there and I'm pretty sure I didn't explicitly watch it. Enjoy the fame :-)

**Comment by pradyunsg** [comment]
> it's just the Python committers being added automatically

Indeed.

> Enjoy the fame :-)

Thanks, I guess.

---

On a completely different note, is anyone else even lukewarm to the idea of making an issue regarding unifying the styling of docs.python.org with python.org over on that repo? ._.

**Comment by pradyunsg** [comment]
Any inputs on this PR? (or that question above :P)

**Comment by jonparrott** [comment]
> Any inputs on this PR? (or that question above :P)

Would still prefer this to happen upstream if at all possible, but, if you feel like this is important enough to do here and now I'm happy to review and merge.

> On a completely different note, is anyone else even lukewarm to the idea of making an issue regarding unifying the styling of docs.python.org with python.org over on that repo? ._.

Go for it, discussion is always good.

**Comment by pradyunsg** [comment]
> Go for it, discussion is always good.

What's the right place for it?

**Comment by pradyunsg** [comment]
> Would still prefer this to happen upstream if at all possible, but, if you feel like this is important enough to do here and now I'm happy to review and merge.

Well then, let's give it a shot upstream. I'm guessing it's gonna be a fairly similar PR there.

**Comment by pradyunsg** [comment]
@jonparrott @pfmoore There's no activity on python/python-docs-theme#4. ._.

Should I ping there or is it a better idea to just get this one done and then proceed upstream?

**Comment by pradyunsg** [comment]
Ping!

@jonparrott Can we go ahead and make this change here?

**Comment by Mariatta** [comment]
IMO this change should be made first here in pypa.
If we learned that everyone likes this new change, and they wished docs.python.org be updated, at that time it can be proposed upstream :)

**Comment by pradyunsg** [comment]
Thanks for the comment @Mariatta! Sounds good to me. :)

**Comment by pradyunsg** [comment]
@jonparrott I don't think this PR was ready for a merge. None the less, I'll make another PR with a more polished look. :)

**Pull request merged**
